### ISSUE TITLE
Linux window appears broken

### ISSUE THREAD

**Issue by crockpotveggies** [chilang/intellij-zeppelin#1]
Hi there! Thanks for making this.

I installed on latest IntelliJ on Ubuntu 16.04. The Zeppelin toolbar appears under the Tools menu. I created a "New Zeppelin Notebook" but unfortunately nothing happened on the IntelliJ side. No windows opened or anything.

I also clicked "Add Zeppelin Paragraph" to the same effect.

What's the expected behavior? Also, willing to contribute on this.

**Comment by crockpotveggies** [comment]
Forgot to mention I checked the host/port and it appears normal. I can see a new notebook being created in Zeppelin, but nothing happens in IntelliJ.

**Comment by chilang** [comment]
The plugin need an opened `.scala` file to work. Updated doc to highlight this.
