### ISSUE TITLE
Zeppelin Idea: No Zeppelin NoteId found.

### ISSUE THREAD

**Issue by nikita-sheremet-java-developer** [chilang/intellij-zeppelin#4]
Hello, I am trying to connect to aws zeppelin which is run on EC2 instance. When I use a link like `https://ec2-00-000-000-000.us-west-2.compute.amazonaws.com/#/notebook/id` via browser I can simply login and run any note. But when I try to do the same thing with intellij idea plugin I got `Zeppelin Idea: No Zeppelin NoteId found.` message in event log.

1. Could you please tell what the problem can be or where I can find any debug information about error details?

1. I have watched your video on Readme page on github. It is a bit confusing.

    1. First of all is it required to have `Hello.scala` for mapping to `Hello` zeppelin note? If so what naming coventioin is used between scala files and zeppelin notes?
   
    1. Does your plugin work with python code or scala only?

It would be the best if you provide a full video - from strating zeppelin, entering credentials, starting creating code. Because now your video is just demostration about plugin not how to run and it is difficult for people who do not have much experience with apach spark and zeppin.

Thanks.

**Comment by chilang** [comment]
You just need to have any `.scala` file open, then start by creating a new Zeppelin Notebook `Tools -> Zeppelin -> New Zeppelin notebook`. 

It will prompt you to enter Zeppelin host name (You can also change this (+username/password if authentication is required) in Intellij settings  `Language and Frameworks -> Zeppelin Notebook`
