### ISSUE TITLE
Question: how do you delete the zeppelin paragraph?

### ISSUE THREAD

**Issue by tomer-ben-david** [chilang/intellij-zeppelin#5]
I just delete the paragraph line from my intellij (paragraph line like `//Paragraph:20180112-201223_1357158255,5`) but when I look at zeppelin web page nothing is deleted...

another small question is it possible to rerun without creating a new paragraph?

**Comment by chilang** [comment]
To delete a paragraph, place your cursor below the `//Paragraph:....` line,  then go to `Tools -> Zeppelin -> Delete Zeppelin paragraph` (you can assign a shortcut to this)

You can re-run with SHIFT+ENTER
